import os

CLI_VERSION = "0.0.1"
BACKEND_URL = "http://localhost:8000"
TOKEN_ENV_VAR = "RESOURSPHERE_TOKEN"
USER_ENV_VAR = "RESOURSPHERE_USER"
PASSWORD_ENV_VAR = "RESOURSPHERE_PASSWORD"
LOCAL_USER_FILE = os.path.expanduser("~/.resoursphere_user")
